version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app_teddy
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres.hnzksnyroathyiugouzu:teddy7735$$@aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: ['yarn', 'start:prod']
